### ISSUE TITLE
Feature Request : Volume as slider

### ISSUE THREAD

**Issue by vmax77** [bschlenk/homebridge-roku#23]
Hi 
Is it possible to treat volume as a slider (dimmable light) instead of the switch?
Thanks

**Comment by bschlenk** [comment]
It probably would be possible. Homebridge actually exposes a speaker service but it wasn’t supported on iOS last time I tried it. I could try that again. And then as a light if that doesn’t work. 

An issue I’m not sure how to work around is that Roku doesn’t let you query the current volume, so you’d never have an accurate slider. If you have any ideas, let me know!

**Comment by bschlenk** [comment]
iOS 12.2 is coming out soon and will support TVs and TV volume natively, and will be a lot better than the current solution. I don't think a slider will be feasible, since as mentioned the Roku TV doesn't let you check what the volume is currently set to. 

Closing this since a slider will not be possible without Roku updating their api, and iOS 12.2 has its own solution.
