### ISSUE TITLE
Volume up and down switch State

### ISSUE THREAD

**Issue by yanhaotan** [bschlenk/homebridge-roku#25]
The volume buttons are currently stateful buttons which makes them stay on after you trigger it, and it also triggers again when you turn it to off state(which is counterintuitive?)

A suggestion to switch them to stateless switch so they revert back to off after a one time trigger.

Also, +-10 seems like a huge leap to me personally would love to have it be +-5 instead if that's more sensible. Just my 2 cents.

Thank you for this awesome plugin!

**Comment by bschlenk** [comment]
I can look into the stateful behavior in a couple days, I just moved and my roku tv is still in storage. 

It would makes sense to be able to configure the increment from the Homebridge config file too. And a default increment of 5 does sound more reasonable. I will look into changing this.

**Comment by tanyanhao96** [comment]
Hey,

Not gonna lie took me a while to find those stuff(total noob here), but here's the edited homebridge-roku.js file.

I've changed 'Power' to 'TV', so you can say "Turn Roku TV on/off" (much more intuitive than Power for me personally).

I've added a space to all the service switch so it's 'Roku HDMI 2' instead of 'RokuHDMI 2', the only thing I couldn't fix yet is the VolumeUp & VolumeDown but that's an easy fix in the Homekit app interface.

********************************************************************************************************

'use strict';

const { Client, keys } = require('roku-client');
const map = require('lodash.map');

let Service;
let Characteristic;

class RokuAccessory {
  constructor(log, config) {
    this.log = log;
    this.name = config.name;

    if (!config.ip) {
      throw new Error(`An ip address is required for plugin ${this.name}`);
    }

    this.appMap = config.appMap;
    this.info = config.info;
    this.roku = new Client(config.ip);
    this.services = [];

    this.muted = false;
    this.volumeLevel = 50;
    this.poweredOn = false;

    this.setup();
  }

  setup() {
    this.services.push(this.setupAccessoryInfo());
    this.services.push(this.setupSwitch());
    this.services.push(this.setupMute());
    this.services.push(this.setupVolumeUp());
    this.services.push(this.setupVolumeDown());
    this.services.push(...this.setupChannels());
  }

  setupAccessoryInfo() {
    const accessoryInfo = new Service.AccessoryInformation();

    accessoryInfo
      .setCharacteristic(Characteristic.Manufacturer, this.info.vendorName)
      .setCharacteristic(Characteristic.Model, this.info.modelName)
      .setCharacteristic(Characteristic.Name, this.info.userDeviceName)
      .setCharacteristic(Characteristic.SerialNumber, this.info.serialNumber);

    return accessoryInfo;
  }

  setupSwitch() {
    const switch_ = new Service.Switch(`${this.name} TV`, 'Power');

    switch_
      .getCharacteristic(Characteristic.On)
      .on('get', callback => callback(null, this.poweredOn))
      .on('set', (value, callback) => {
        this.poweredOn = value;
        this.roku.keypress('Power')
          .then(() => callback(null))
          .catch(callback);
      });

    return switch_;
  }

  setupMute() {
    // Speaker seems to be unsupported, emmulating with a switch
    const volume = new Service.Switch(`${this.name} Mute`, 'Mute');

    volume
      .getCharacteristic(Characteristic.On)
      .on('get', callback => callback(null, this.muted))
      .on('set', (value, callback) => {
        this.muted = value;
        const command = this.roku.command()
          // toggling the volume up and down is a reliable way to unmute
          // the TV if the current state is not known
          .volumeDown()
          .volumeUp();

        if (this.muted) {
          command.volumeMute();
        }

        command.send()
          .then(() => callback(null))
          .catch(callback);
      });

    return volume;
  }

  setupVolumeUp() {
    return this.setupVolume(keys.VOLUME_UP);
  }

  setupVolumeDown() {
    return this.setupVolume(keys.VOLUME_DOWN);
  }

  setupVolume(key) {
    const volume = new Service.Switch(`${this.name} ${key}`, key);

    volume
      .getCharacteristic(Characteristic.On)
      .on('get', callback => callback(null, false))
      .on('set', (value, callback) => {
        this.roku.command()
          .keypress(key, 5)
          .send()
          .then(() => callback(null, false))
          .catch(callback);
      });

    return volume;
  }

  setupChannels() {
    return map(this.appMap, (id, name) => this.setupChannel(name, id));
  }

  setupChannel(name, id) {
    const channel = new Service.Switch(`${this.name} ${name}`, name);

    channel
      .getCharacteristic(Characteristic.On)
      .on('get', (callback) => {
        this.roku.active()
          .then((app) => {
            callback(null, app && app.id === id);
          })
          .catch(callback);
      })
      .on('set', (value, callback) => {
        if (value) {
          this.roku.launch(id)
            .then(() => callback(null, true))
            .catch(callback);
        } else {
          this.roku.keypress(keys.HOME)
            .then(() => callback(null, false))
            .catch(callback);
        }
      });

    return channel;
  }

  getServices() {
    return this.services;
  }
}

module.exports = (homebridge) => {
  console.log(`homebridge API version: ${homebridge.version}`);

  ({ Service, Characteristic } = homebridge.hap);

  homebridge.registerAccessory('homebridge-roku', 'Roku', RokuAccessory);
};

**Comment by bschlenk** [comment]
Are you familiar with making pull requests? https://help.github.com/articles/creating-a-pull-request/
Typically you don't just paste code into a github issue. You would fork the repo, make a commit on your copy, and then create a pull request.

Also it is generally best practice to create a separate issue for each distinct request. This issue was initially about volume up and down switch state, but this is for the names used for each switch. I'm happy to incorporate these changes (at least for adding the spaces), but it would be better as a separate issue.

**Comment by tanyanhao96** [comment]
My apologies, I am really really new to GitHub (my first post actually), I'll look into the pull request and open up a separate issue for the names.

**Comment by bschlenk** [comment]
That's okay! Gotta learn somehow.

For the names, I just updated them to have spaces, but I'm not sure about changing power to TV. Is power exclusive to Roku TVs? It might make more sense to just remove Power so you can say "turn on roku", which is more accommodating if there are other Roku devices besides TVs which can be turned on and off.

**Comment by tanyanhao96** [comment]
Roku TV seems to work pretty well for me since I also have Fire TV that I cast from the Echo dot all the time I am used to saying 'TV' at the end of it.

But I don't see why not Roku itself won't work, not sure if Power if exclusive to Roku.

**Comment by bschlenk** [comment]
The latest homebridge-roku let you set `volumeIncrement` and `volumeDecrement` in the config file, which is explained more [in the readme](https://github.com/bschlenk/homebridge-roku#configuration). 

With the latest iOS, 12.2, HomeKit will natively support televisions, so volume up/down will be a lot more intuitive. It will let you control your Roku tv from the apple tv remote on your phone, which lets you use your phone's volume buttons to control the TV volume. You can watch the progress of the changes here: https://github.com/bschlenk/homebridge-roku/pull/63. It will be a while before iOS 12.2 is released though, and those changes won't be merged in until after that.

**Comment by bschlenk** [comment]
[3.0.0-alpha.1](https://github.com/bschlenk/homebridge-roku/tree/develop) supports changing the volume increment, and with the control center remote, supports changing the volume with the phone's volume buttons.
